### ISSUE TITLE
[BUG] play_dm broken ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by deepbluesea** [nickwalton/AIDungeon#236]
`Traceback (most recent call last):
  File "play_dm.py", line 51, in <module>
    play_dm()
  File "play_dm.py", line 29, in play_dm
    context, prompt = select_game()
ValueError: too many values to unpack (expected 2)`

does not work at all

**Comment by ben-bay** [comment]
What OS did you run this on? What version of python?

**Comment by ben-bay** [comment]
Also what branch, master or develop?

**Comment by deepbluesea** [comment]
> What OS did you run this on? What version of python?

ubuntu google colab
python 3.6
> Also what branch, master or develop?

default, watch is develop
